apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: my-website
spec:
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        # image: my-website
        imagePullPolicy: Always
        image: gcr.io/my-website-169905/my-website:latest
        ports:
        - containerPort: 8080
