apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: my-website
spec:
  replicas: 3
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: my-website
        #image: gcr.io/my-website?/my-website?
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
