apiVersion: v1
kind: Service
metadata:
  name: my-website
spec:
  selector:
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
  # gce load balancer
  type: LoadBalancer
  # cluster-1
  # loadBalancerIP: 35.197.4.146
  # cluster-2
  loadBalancerIP: 35.192.0.146
